services:
  api:
    build:
      context: .
      dockerfile: ./compose/production/api/Dockerfile
    image: fastapi
    container_name: fastapi
    environment:
      - MODE=prod
    env_file:
      - ./.env
    command: /start
    ports:
      - '8000:8000'
